export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADJUST_TO_CART = "ADJUST_TO_CART";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
// export const SELECT_FROM_CART = "SELECT_FROM_CART";
// export const QUANTITY_SELECT = "QUANTITY_SELECT";
